CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(100) NOT NULL,
    email VARCHAR(50) UNIQUE NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY(id),
    CONSTRAINT uq_user_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS item_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    requester_id BIGINT NOT NULL,
    description TEXT NOT NULL,
    created TIMESTAMP,
    CONSTRAINT pk_item_requests PRIMARY KEY(id),
    CONSTRAINT fk_item_requests_users FOREIGN KEY(requester_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    owner_id BIGINT NOT NULL,
    request_id BIGINT,
    item_name VARCHAR(100) NOT NULL,
    description VARCHAR(300),
    available BOOLEAN NOT NULL,
    CONSTRAINT pk_items PRIMARY KEY(id),
    CONSTRAINT fk_users_items FOREIGN KEY(owner_id) REFERENCES users(id),
    CONSTRAINT fk_item_requests_items FOREIGN KEY(request_id) REFERENCES item_requests(id)
);

CREATE TABLE IF NOT EXISTS bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_time TIMESTAMP,
    end_time TIMESTAMP,
    item_id BIGINT NOT NULL,
    booker_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    CONSTRAINT pk_bookings PRIMARY KEY(id),
    CONSTRAINT fk_bookings_items FOREIGN KEY(item_id) REFERENCES items(id),
    CONSTRAINT fk_bookings_users FOREIGN KEY(booker_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    author_id BIGINT NOT NULL,
    item_id BIGINT NOT NULL,
    text TEXT,
    created TIMESTAMP,
    CONSTRAINT pk_comments PRIMARY KEY(id),
    CONSTRAINT fk_comments_users FOREIGN KEY(author_id) REFERENCES users(id),
    CONSTRAINT fk_comments_items FOREIGN KEY(item_id) REFERENCES items(id)
);
